package com.lsts.webservice.cxf.client.device_transfer.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-03-24T14:34:04.408+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://device.ws.ts.zjpt/", name = "TsDeivceService")
@XmlSeeAlso({ObjectFactory.class})
public interface TsDeivceService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateParamInfo", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.UpdateParamInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateParamInfoResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.UpdateParamInfoResponse")
    public java.lang.String updateParamInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "insertDeviceInfo", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.InsertDeviceInfo")
    @WebMethod
    @ResponseWrapper(localName = "insertDeviceInfoResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.InsertDeviceInfoResponse")
    public java.lang.String insertDeviceInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "geDeviceInfoByRegCode", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.GeDeviceInfoByRegCode")
    @WebMethod
    @ResponseWrapper(localName = "geDeviceInfoByRegCodeResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.GeDeviceInfoByRegCodeResponse")
    public java.lang.String geDeviceInfoByRegCode(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "regCode", targetNamespace = "")
        java.lang.String regCode,
        @WebParam(name = "DeviceType", targetNamespace = "")
        java.lang.String deviceType
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatDeviceInfo", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.UpdatDeviceInfo")
    @WebMethod
    @ResponseWrapper(localName = "updatDeviceInfoResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.UpdatDeviceInfoResponse")
    public java.lang.String updatDeviceInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "geDeviceInfoByQrCode", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.GeDeviceInfoByQrCode")
    @WebMethod
    @ResponseWrapper(localName = "geDeviceInfoByQrCodeResponse", targetNamespace = "http://device.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.server.GeDeviceInfoByQrCodeResponse")
    public java.lang.String geDeviceInfoByQrCode(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "QrCode", targetNamespace = "")
        java.lang.String qrCode,
        @WebParam(name = "DeviceType", targetNamespace = "")
        java.lang.String deviceType
    );
}
