package com.lsts.webservice.cxf.client.device_transfer.inspect.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-03-24T16:49:07.202+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebServiceClient(name = "tsInspectionService", 
                  wsdlLocation = "http://192.168.1.35:9090/cxfws/tsInspectionService?wsdl",
                  targetNamespace = "http://impl.inspect.ws.ts.zjpt/") 
public class TsInspectionService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.inspect.ws.ts.zjpt/", "tsInspectionService");
    public final static QName TsInspectionServiceImplPort = new QName("http://impl.inspect.ws.ts.zjpt/", "TsInspectionServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.101:9090/cxfws/tsInspectionService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TsInspectionService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.1.35:9090/cxfws/tsInspectionService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TsInspectionService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TsInspectionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TsInspectionService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TsInspectionService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TsInspectionService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TsInspectionService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TsInspectionService
     */
    @WebEndpoint(name = "TsInspectionServiceImplPort")
    public com.lsts.webservice.cxf.client.device_transfer.inspect.TsInspectionService getTsInspectionServiceImplPort() {
        return super.getPort(TsInspectionServiceImplPort, com.lsts.webservice.cxf.client.device_transfer.inspect.TsInspectionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TsInspectionService
     */
    @WebEndpoint(name = "TsInspectionServiceImplPort")
    public com.lsts.webservice.cxf.client.device_transfer.inspect.TsInspectionService getTsInspectionServiceImplPort(WebServiceFeature... features) {
        return super.getPort(TsInspectionServiceImplPort, com.lsts.webservice.cxf.client.device_transfer.inspect.TsInspectionService.class, features);
    }

}
