package webService.adddt;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-09-28T11:16:46.376+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebServiceClient(name = "JyDataNewJy", 
                  wsdlLocation = "http://119.6.254.76:9014/JyDataNewJy?wsdl",
                  targetNamespace = "http://service.ws.cxf.zytx.com/") 
public class JyDataNewJy_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.cxf.zytx.com/", "JyDataNewJy");
    public final static QName JyDataNewJyServiceImpPort = new QName("http://service.ws.cxf.zytx.com/", "JyDataNewJyServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://119.6.254.76:9014/JyDataNewJy?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JyDataNewJy_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://119.6.254.76:9014/JyDataNewJy?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JyDataNewJy_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JyDataNewJy_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JyDataNewJy_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JyDataNewJy_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JyDataNewJy_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JyDataNewJy_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns JyDataNewJyService
     */
    @WebEndpoint(name = "JyDataNewJyServiceImpPort")
    public JyDataNewJyService getJyDataNewJyServiceImpPort() {
        return super.getPort(JyDataNewJyServiceImpPort, JyDataNewJyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JyDataNewJyService
     */
    @WebEndpoint(name = "JyDataNewJyServiceImpPort")
    public JyDataNewJyService getJyDataNewJyServiceImpPort(WebServiceFeature... features) {
        return super.getPort(JyDataNewJyServiceImpPort, JyDataNewJyService.class, features);
    }

}
