
package com.lsts.webservice.cxf.client.device_transfer.server;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.lsts.webservice.cxf.client.device_transfer.server.impl.TsDeviceService;

import net.sf.json.JSONObject;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-03-24T14:34:04.353+08:00
 * Generated source version: 2.4.3
 * 
 */
public final class TsDeivceService_TsDeivceServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.device.ws.ts.zjpt/", "tsDeviceService");

    private TsDeivceService_TsDeivceServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TsDeviceService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TsDeviceService ss = new TsDeviceService(wsdlURL, SERVICE_NAME);
        TsDeivceService port = ss.getTsDeivceServiceImplPort();  
        
        
        
        String result = port.geDeviceInfoByQrCode("fg54gsd","4yukjngf43", "123456", "3");
    	
    	System.out.println(result);
    	
    	JSONObject jsonObject = JSONObject.fromObject(result);
    	
//    	 JSONArray list=(JSONArray)jsonObject.getJSONArray("SUCCESS");
//    	 
//    		System.out.println((String)jsonObject.get("SUCCESS:"));
//        
//        {
//        System.out.println("Invoking updateParamInfo...");
//        java.lang.String _updateParamInfo_account = "";
//        java.lang.String _updateParamInfo_password = "";
//        java.lang.String _updateParamInfo_content = "";
//        java.lang.String _updateParamInfo__return = port.updateParamInfo(_updateParamInfo_account, _updateParamInfo_password, _updateParamInfo_content);
//        System.out.println("updateParamInfo.result=" + _updateParamInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking insertDeviceInfo...");
//        java.lang.String _insertDeviceInfo_account = "";
//        java.lang.String _insertDeviceInfo_password = "";
//        java.lang.String _insertDeviceInfo_content = "";
//        java.lang.String _insertDeviceInfo__return = port.insertDeviceInfo(_insertDeviceInfo_account, _insertDeviceInfo_password, _insertDeviceInfo_content);
//        System.out.println("insertDeviceInfo.result=" + _insertDeviceInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking geDeviceInfoByRegCode...");
//        java.lang.String _geDeviceInfoByRegCode_account = "";
//        java.lang.String _geDeviceInfoByRegCode_password = "";
//        java.lang.String _geDeviceInfoByRegCode_regCode = "";
//        java.lang.String _geDeviceInfoByRegCode_deviceType = "";
//        java.lang.String _geDeviceInfoByRegCode__return = port.geDeviceInfoByRegCode(_geDeviceInfoByRegCode_account, _geDeviceInfoByRegCode_password, _geDeviceInfoByRegCode_regCode, _geDeviceInfoByRegCode_deviceType);
//        System.out.println("geDeviceInfoByRegCode.result=" + _geDeviceInfoByRegCode__return);
//
//
//        }
//        {
//        System.out.println("Invoking updatDeviceInfo...");
//        java.lang.String _updatDeviceInfo_account = "";
//        java.lang.String _updatDeviceInfo_password = "";
//        java.lang.String _updatDeviceInfo_content = "";
//        java.lang.String _updatDeviceInfo__return = port.updatDeviceInfo(_updatDeviceInfo_account, _updatDeviceInfo_password, _updatDeviceInfo_content);
//        System.out.println("updatDeviceInfo.result=" + _updatDeviceInfo__return);
//
//
//        }
//        {
//        System.out.println("Invoking geDeviceInfoByQrCode...");
//        java.lang.String _geDeviceInfoByQrCode_account = "";
//        java.lang.String _geDeviceInfoByQrCode_password = "";
//        java.lang.String _geDeviceInfoByQrCode_qrCode = "";
//        java.lang.String _geDeviceInfoByQrCode_deviceType = "";
//        java.lang.String _geDeviceInfoByQrCode__return = port.geDeviceInfoByQrCode(_geDeviceInfoByQrCode_account, _geDeviceInfoByQrCode_password, _geDeviceInfoByQrCode_qrCode, _geDeviceInfoByQrCode_deviceType);
//        System.out.println("geDeviceInfoByQrCode.result=" + _geDeviceInfoByQrCode__return);
//
//
//        }
//
//        System.exit(0);
    }

}
