package webService.dqjy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-09-28T10:56:01.245+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebServiceClient(name = "JyDataJy", 
                  wsdlLocation = "http://119.6.254.76:9014/JyDataJy?wsdl",
                  targetNamespace = "http://service.ws.cxf.zytx.com/") 
public class JyDataJy_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.ws.cxf.zytx.com/", "JyDataJy");
    public final static QName JyDataJyServiceImpPort = new QName("http://service.ws.cxf.zytx.com/", "JyDataJyServiceImpPort");
    static {
        URL url = null;
        try {
            url = new URL("http://119.6.254.76:9014/JyDataJy?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(JyDataJy_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://119.6.254.76:9014/JyDataJy?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public JyDataJy_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public JyDataJy_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JyDataJy_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JyDataJy_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JyDataJy_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public JyDataJy_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns JyDataJyService
     */
    @WebEndpoint(name = "JyDataJyServiceImpPort")
    public JyDataJyService getJyDataJyServiceImpPort() {
        return super.getPort(JyDataJyServiceImpPort, JyDataJyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JyDataJyService
     */
    @WebEndpoint(name = "JyDataJyServiceImpPort")
    public JyDataJyService getJyDataJyServiceImpPort(WebServiceFeature... features) {
        return super.getPort(JyDataJyServiceImpPort, JyDataJyService.class, features);
    }

}
