package com.lsts.webservice.cxf.client.device_transfer.waring;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import com.lsts.webservice.cxf.client.device_transfer.waring.impl.WarningDealService;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-03-27T15:35:58.086+08:00
 * Generated source version: 2.4.3
 * 
 */
public final class WarningDealService_WarningDealServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.warning.ws.ts.zjpt/", "warningDealService");

    private WarningDealService_WarningDealServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WarningDealService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WarningDealService ss = new WarningDealService(wsdlURL, SERVICE_NAME);
        com.lsts.webservice.cxf.client.device_transfer.waring.WarningDealService port =  ss.getWarningDealServiceImplPort();  
        
        String result =  port.updateWarningDeal("zdfdf342", "adfghgd43", "{\"PARAM\":{\"device_registration_code\":\"35005101082010080015\",\"deal_status\":\"111\",\"deal_man\":\"111\",\"deal_time\":\"1992-02-12\",\"deal_receive_man\":\"ces2\",\"inspect_org\":\"1\",\"deal_unit\":\"19989\",\"deal_mark\":\"测试\"}}");
        System.out.println(result);
        {
//        System.out.println("Invoking updateWarningDeal...");
//        java.lang.String _updateWarningDeal_account = "";
//        java.lang.String _updateWarningDeal_password = "";
//        java.lang.String _updateWarningDeal_content = "";
//        java.lang.String _updateWarningDeal__return = ((com.lsts.webservice.cxf.client.device_transfer.waring.WarningDealService) port).updateWarningDeal(_updateWarningDeal_account, _updateWarningDeal_password, _updateWarningDeal_content);
//        System.out.println("updateWarningDeal.result=" + _updateWarningDeal__return);


        }

        System.exit(0);
    }

}
