package webService.regularInspect;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-09-18T10:57:32.814+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://service.ws.cxf.zytx.com/", name = "JyDataJyService")
@XmlSeeAlso({ObjectFactory.class})
public interface JyDataJyService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "jyDataQuery", targetNamespace = "http://service.ws.cxf.zytx.com/", className = "webService.regularInspect.JyDataQuery")
    @WebMethod
    @ResponseWrapper(localName = "jyDataQueryResponse", targetNamespace = "http://service.ws.cxf.zytx.com/", className = "webService.regularInspect.JyDataQueryResponse")
    public java.lang.String jyDataQuery(
        @WebParam(name = "xmlStr", targetNamespace = "")
        java.lang.String xmlStr
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "jyDataJy", targetNamespace = "http://service.ws.cxf.zytx.com/", className = "webService.regularInspect.JyDataJy")
    @WebMethod
    @ResponseWrapper(localName = "jyDataJyResponse", targetNamespace = "http://service.ws.cxf.zytx.com/", className = "webService.regularInspect.JyDataJyResponse")
    public java.lang.String jyDataJy(
        @WebParam(name = "xmlStr", targetNamespace = "")
        java.lang.String xmlStr
    );
}
