package com.lsts.webservice.cxf.client.device_transfer.inspect;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-03-24T16:49:07.194+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://inspect.ws.ts.zjpt/", name = "TsInspectionService")
@XmlSeeAlso({ObjectFactory.class})
public interface TsInspectionService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateInspectionInfo", targetNamespace = "http://inspect.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.inspect.UpdateInspectionInfo")
    @WebMethod
    @ResponseWrapper(localName = "updateInspectionInfoResponse", targetNamespace = "http://inspect.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.inspect.UpdateInspectionInfoResponse")
    public java.lang.String updateInspectionInfo(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );
}
