package com.lsts.webservice.cxf.client.device_transfer.waring;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.3
 * 2017-03-27T15:35:58.127+08:00
 * Generated source version: 2.4.3
 * 
 */
@WebService(targetNamespace = "http://warning.ws.ts.zjpt/", name = "WarningDealService")
@XmlSeeAlso({ObjectFactory.class})
public interface WarningDealService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateWarningDeal", targetNamespace = "http://warning.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.waring.UpdateWarningDeal")
    @WebMethod
    @ResponseWrapper(localName = "updateWarningDealResponse", targetNamespace = "http://warning.ws.ts.zjpt/", className = "com.lsts.webservice.cxf.client.device_transfer.waring.UpdateWarningDealResponse")
    public java.lang.String updateWarningDeal(
        @WebParam(name = "account", targetNamespace = "")
        java.lang.String account,
        @WebParam(name = "password", targetNamespace = "")
        java.lang.String password,
        @WebParam(name = "content", targetNamespace = "")
        java.lang.String content
    );
}
